kind: pipeline
name: Installation

steps:

- name: Import the captions
  image: appleboy/drone-ssh
  pull: if-not-exists
  settings:
    host:
        from_secret: scp_host
    user: 
        from_secret: scp_user
    key:
        from_secret: scp_key
    script:
    - cd /var/www/tools.repair.wiki/data
    - git pull
    - cd ../prod
    - php import.php
    trigger:
        branch:
        - master
